INSERT INTO `t_estado` (`codigo`, `nombre`, `estatus`) VALUES
(1, 'Amazonas', 'A'),
(2, 'Anzoátegui', 'A'),
(3, 'Apure', 'A'),
(4, 'Aragua', 'A'),
(5, 'Barinas', 'A'),
(6, 'Bolívar', 'A'),
(7, 'Carabobo', 'A'),
(8, 'Cojedes', 'A'),
(9, 'Delta Amacuro', 'A'),
(10, 'Falcón', 'A'),
(11, 'Guárico', 'A'),
(12, 'Lara', 'A'),
(13, 'Mérida', 'A'),
(14, 'Miranda', 'A'),
(15, 'Monagas', 'A'),
(16, 'Nueva Esparta', 'A'),
(17, 'Portuguesa', 'A'),
(18, 'Sucre', 'A'),
(19, 'Táchira', 'A'),
(20, 'Trujillo', 'A'),
(21, 'Vargas', 'A'),
(22, 'Yaracuy', 'A'),
(23, 'Zulia', 'A'),
(24, 'Distrito Capital', 'A'),
(25, 'Dependencias Federales', 'A');